FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY configs/connectionStrings_dev.json ./configs/connectionStrings_dev.json
COPY ["Surveys.Migrations/Surveys.Migrations.csproj", "Surveys.Migrations/"]
RUN dotnet restore "Surveys.Migrations/Surveys.Migrations.csproj"

COPY ["Surveys.Migrations/", "Surveys.Migrations/"]

RUN dotnet publish "Surveys.Migrations/Surveys.Migrations.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Surveys.Migrations.dll"]